import { test } from "node:test";
import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
// Tests compile separately after the production build, then import the built CLI.
// @ts-expect-error build/index.js is generated by npm test before test compilation.
import { handleToolCall, normalizeGitHubRepo } from "../build/index.js";

const here = dirname(fileURLToPath(import.meta.url));
const buildEntry = join(here, "..", "build", "index.js");
const pkg = JSON.parse(
  readFileSync(join(here, "..", "package.json"), "utf8"),
) as { version: string };

// Issue #14: the server must advertise the real package version, not a
// stale hardcoded one, and --version must agree with package.json.
test("#14: --version prints the package.json version", () => {
  const out = execFileSync(process.execPath, [buildEntry, "--version"], {
    encoding: "utf8",
    env: {},
  }).trim();
  assert.equal(out, pkg.version);
});

test("#14: MCP Server is constructed with PKG_VERSION, not a hardcoded version", () => {
  const built = readFileSync(buildEntry, "utf8");
  assert.match(
    built,
    /new Server\(\{ name: "taskbounty-mcp-server", version: PKG_VERSION \}/,
  );
  assert.ok(
    !built.includes('version: "0.1.0"'),
    "build must not contain a hardcoded 0.1.0 server version",
  );
});

test("normalizes supported GitHub repo strings", () => {
  assert.equal(normalizeGitHubRepo("owner/name"), "owner/name");
  assert.equal(normalizeGitHubRepo("https://github.com/owner/name"), "owner/name");
  assert.equal(normalizeGitHubRepo("https://github.com/owner/name.git"), "owner/name");
  assert.equal(normalizeGitHubRepo("https://github.com/owner/name/"), "owner/name");
});

test("rejects malformed GitHub repo strings", () => {
  assert.equal(normalizeGitHubRepo("not-a-repo"), null);
});

test("submit_pr reports a missing required argument before network access", async () => {
  const result = await handleToolCall("submit_pr", {
    task_id: "task_123",
    result_text: "Fixed with regression coverage.",
    external_link: "https://github.com/owner/repo/pull/1",
  });

  assert.equal(result.isError, true);
  assert.deepEqual(result.content, [
    { type: "text", text: "agent_id is required" },
  ]);
});
